package com.software.dm.swallow.stormy.ssm.sys.entity;

import java.util.Date;

public class SysUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLATFORM.T_SYS_USER.LOGIN_USER_NAME
     *
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    private String loginUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLATFORM.T_SYS_USER.ID
     *
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLATFORM.T_SYS_USER.USER_NAME
     *
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLATFORM.T_SYS_USER.LOGIN_USER_PWD
     *
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    private String loginUserPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLATFORM.T_SYS_USER.USER_STATUS
     *
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    private String userStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLATFORM.T_SYS_USER.USER_AREA
     *
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    private String userArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLATFORM.T_SYS_USER.USER_PHONE
     *
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLATFORM.T_SYS_USER.USER_EMAIL
     *
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    private String userEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLATFORM.T_SYS_USER.CREATE_TIME
     *
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLATFORM.T_SYS_USER.USER_LAST_LOGIN
     *
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    private Date userLastLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLATFORM.T_SYS_USER.USER_LAST_LOGIN_IP
     *
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    private String userLastLoginIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLATFORM.T_SYS_USER.ACCESSUSER
     *
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    private String accessuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLATFORM.T_SYS_USER.USER_PARENT_ID
     *
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    private String userParentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLATFORM.T_SYS_USER.USER_BELONG
     *
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    private String userBelong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLATFORM.T_SYS_USER.USER_AUDIT
     *
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    private String userAudit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLATFORM.T_SYS_USER.USER_LOGIN_IP
     *
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    private String userLoginIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLATFORM.T_SYS_USER.USER_LOGIN_TIME
     *
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    private Date userLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLATFORM.T_SYS_USER.USER_DEPARTMENT
     *
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    private String userDepartment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLATFORM.T_SYS_USER.LOGIN_USER_NAME
     *
     * @return the value of PLATFORM.T_SYS_USER.LOGIN_USER_NAME
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    public String getLoginUserName() {
        return loginUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLATFORM.T_SYS_USER.LOGIN_USER_NAME
     *
     * @param loginUserName the value for PLATFORM.T_SYS_USER.LOGIN_USER_NAME
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    public void setLoginUserName(String loginUserName) {
        this.loginUserName = loginUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLATFORM.T_SYS_USER.ID
     *
     * @return the value of PLATFORM.T_SYS_USER.ID
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLATFORM.T_SYS_USER.ID
     *
     * @param id the value for PLATFORM.T_SYS_USER.ID
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLATFORM.T_SYS_USER.USER_NAME
     *
     * @return the value of PLATFORM.T_SYS_USER.USER_NAME
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLATFORM.T_SYS_USER.USER_NAME
     *
     * @param userName the value for PLATFORM.T_SYS_USER.USER_NAME
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLATFORM.T_SYS_USER.LOGIN_USER_PWD
     *
     * @return the value of PLATFORM.T_SYS_USER.LOGIN_USER_PWD
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    public String getLoginUserPwd() {
        return loginUserPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLATFORM.T_SYS_USER.LOGIN_USER_PWD
     *
     * @param loginUserPwd the value for PLATFORM.T_SYS_USER.LOGIN_USER_PWD
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    public void setLoginUserPwd(String loginUserPwd) {
        this.loginUserPwd = loginUserPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLATFORM.T_SYS_USER.USER_STATUS
     *
     * @return the value of PLATFORM.T_SYS_USER.USER_STATUS
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    public String getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLATFORM.T_SYS_USER.USER_STATUS
     *
     * @param userStatus the value for PLATFORM.T_SYS_USER.USER_STATUS
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    public void setUserStatus(String userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLATFORM.T_SYS_USER.USER_AREA
     *
     * @return the value of PLATFORM.T_SYS_USER.USER_AREA
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    public String getUserArea() {
        return userArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLATFORM.T_SYS_USER.USER_AREA
     *
     * @param userArea the value for PLATFORM.T_SYS_USER.USER_AREA
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    public void setUserArea(String userArea) {
        this.userArea = userArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLATFORM.T_SYS_USER.USER_PHONE
     *
     * @return the value of PLATFORM.T_SYS_USER.USER_PHONE
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLATFORM.T_SYS_USER.USER_PHONE
     *
     * @param userPhone the value for PLATFORM.T_SYS_USER.USER_PHONE
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLATFORM.T_SYS_USER.USER_EMAIL
     *
     * @return the value of PLATFORM.T_SYS_USER.USER_EMAIL
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLATFORM.T_SYS_USER.USER_EMAIL
     *
     * @param userEmail the value for PLATFORM.T_SYS_USER.USER_EMAIL
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLATFORM.T_SYS_USER.CREATE_TIME
     *
     * @return the value of PLATFORM.T_SYS_USER.CREATE_TIME
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLATFORM.T_SYS_USER.CREATE_TIME
     *
     * @param createTime the value for PLATFORM.T_SYS_USER.CREATE_TIME
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLATFORM.T_SYS_USER.USER_LAST_LOGIN
     *
     * @return the value of PLATFORM.T_SYS_USER.USER_LAST_LOGIN
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    public Date getUserLastLogin() {
        return userLastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLATFORM.T_SYS_USER.USER_LAST_LOGIN
     *
     * @param userLastLogin the value for PLATFORM.T_SYS_USER.USER_LAST_LOGIN
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    public void setUserLastLogin(Date userLastLogin) {
        this.userLastLogin = userLastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLATFORM.T_SYS_USER.USER_LAST_LOGIN_IP
     *
     * @return the value of PLATFORM.T_SYS_USER.USER_LAST_LOGIN_IP
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    public String getUserLastLoginIp() {
        return userLastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLATFORM.T_SYS_USER.USER_LAST_LOGIN_IP
     *
     * @param userLastLoginIp the value for PLATFORM.T_SYS_USER.USER_LAST_LOGIN_IP
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    public void setUserLastLoginIp(String userLastLoginIp) {
        this.userLastLoginIp = userLastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLATFORM.T_SYS_USER.ACCESSUSER
     *
     * @return the value of PLATFORM.T_SYS_USER.ACCESSUSER
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    public String getAccessuser() {
        return accessuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLATFORM.T_SYS_USER.ACCESSUSER
     *
     * @param accessuser the value for PLATFORM.T_SYS_USER.ACCESSUSER
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    public void setAccessuser(String accessuser) {
        this.accessuser = accessuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLATFORM.T_SYS_USER.USER_PARENT_ID
     *
     * @return the value of PLATFORM.T_SYS_USER.USER_PARENT_ID
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    public String getUserParentId() {
        return userParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLATFORM.T_SYS_USER.USER_PARENT_ID
     *
     * @param userParentId the value for PLATFORM.T_SYS_USER.USER_PARENT_ID
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    public void setUserParentId(String userParentId) {
        this.userParentId = userParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLATFORM.T_SYS_USER.USER_BELONG
     *
     * @return the value of PLATFORM.T_SYS_USER.USER_BELONG
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    public String getUserBelong() {
        return userBelong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLATFORM.T_SYS_USER.USER_BELONG
     *
     * @param userBelong the value for PLATFORM.T_SYS_USER.USER_BELONG
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    public void setUserBelong(String userBelong) {
        this.userBelong = userBelong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLATFORM.T_SYS_USER.USER_AUDIT
     *
     * @return the value of PLATFORM.T_SYS_USER.USER_AUDIT
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    public String getUserAudit() {
        return userAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLATFORM.T_SYS_USER.USER_AUDIT
     *
     * @param userAudit the value for PLATFORM.T_SYS_USER.USER_AUDIT
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    public void setUserAudit(String userAudit) {
        this.userAudit = userAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLATFORM.T_SYS_USER.USER_LOGIN_IP
     *
     * @return the value of PLATFORM.T_SYS_USER.USER_LOGIN_IP
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    public String getUserLoginIp() {
        return userLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLATFORM.T_SYS_USER.USER_LOGIN_IP
     *
     * @param userLoginIp the value for PLATFORM.T_SYS_USER.USER_LOGIN_IP
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    public void setUserLoginIp(String userLoginIp) {
        this.userLoginIp = userLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLATFORM.T_SYS_USER.USER_LOGIN_TIME
     *
     * @return the value of PLATFORM.T_SYS_USER.USER_LOGIN_TIME
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    public Date getUserLoginTime() {
        return userLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLATFORM.T_SYS_USER.USER_LOGIN_TIME
     *
     * @param userLoginTime the value for PLATFORM.T_SYS_USER.USER_LOGIN_TIME
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    public void setUserLoginTime(Date userLoginTime) {
        this.userLoginTime = userLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLATFORM.T_SYS_USER.USER_DEPARTMENT
     *
     * @return the value of PLATFORM.T_SYS_USER.USER_DEPARTMENT
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    public String getUserDepartment() {
        return userDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLATFORM.T_SYS_USER.USER_DEPARTMENT
     *
     * @param userDepartment the value for PLATFORM.T_SYS_USER.USER_DEPARTMENT
     * @mbg.generated Tue Jun 26 16:36:32 CST 2018
     */
    public void setUserDepartment(String userDepartment) {
        this.userDepartment = userDepartment;
    }

    @Override
    public String toString() {
        return "SysUser{" +
                "loginUserName='" + loginUserName + '\'' +
                ", id='" + id + '\'' +
                ", userName='" + userName + '\'' +
                ", loginUserPwd='" + loginUserPwd + '\'' +
                ", userStatus='" + userStatus + '\'' +
                ", userArea='" + userArea + '\'' +
                ", userPhone='" + userPhone + '\'' +
                ", userEmail='" + userEmail + '\'' +
                ", createTime=" + createTime +
                ", userLastLogin=" + userLastLogin +
                ", userLastLoginIp='" + userLastLoginIp + '\'' +
                ", accessuser='" + accessuser + '\'' +
                ", userParentId='" + userParentId + '\'' +
                ", userBelong='" + userBelong + '\'' +
                ", userAudit='" + userAudit + '\'' +
                ", userLoginIp='" + userLoginIp + '\'' +
                ", userLoginTime=" + userLoginTime +
                ", userDepartment='" + userDepartment + '\'' +
                '}';
    }
}